### PR TITLE
Adding new muon particle which fits into the laser physics list inste…

### PR DESCRIPTION
**Pull request by calcuttj**
This includes a new muon-like particle that is used solely for the laser simulation. Most of its physics has been turned off. The recent physics list which turns off the mu+ physics by hand has been modified to use this particle, and the mu+ physics has been restored

### CODE REVIEW

**Comment by hanswenzel** [comment]
Hi 


in principle it's fine to merge. I am not sure that we want to keep the Geant4 license header since this is not distributed with Geant4. May be we want to say this is a modification of the Geant4 file bla bla bla but then get rid of the license header and use the artg4tk header instead.  Also the comments relate to Muonplus so that should be changed to muon laser (if you want to keep this name). May be the name should be something like Laser like particle. 
My apologies for getting back so late  ( I was sick) 


Cheers Hans

**Comment by calcuttj** [comment]
No worries Hans, sorry to hear about your illness. Hope you're feeling better.

I copied the file from Geant4 which is why the license header remains, I'll remove. 

As far as the name, maybe something like PseudoLaser

**Comment by knoepfel** [comment]
@calcuttj and @hanswenzel, we need to understand the licensing implications of this PR before we move forward.  Can you point us to the G4 file you used as a template for your code?

**Comment by calcuttj** [comment]
@knoepfel 

https://github.com/Geant4/geant4/blob/master/source/particles/leptons/src/G4MuonPlus.cc
https://github.com/Geant4/geant4/blob/master/source/particles/leptons/include/G4MuonPlus.hh

**Comment by calcuttj** [comment]
On the topic of licenses, lots/all of the lists in https://github.com/art-framework-suite/art-g4tk/tree/develop/artg4tk/lists have the Geant4 license at the top

**Comment by hanswenzel** [comment]
> On the topic of licenses, lots/all of the lists in https://github.com/art-framework-suite/art-g4tk/tree/develop/artg4tk/lists have the Geant4 license at the top

That should be changed. I don't think I was asked to review when this lists were added. I will be on vacation until the middle of next week. Then I will have a look. 


Hans

**Comment by knoepfel** [comment]
@hanswenzel, we created an issue (#2) related to the licensing information included in the code.

**Comment by calcuttj** [comment]
Thank you for the merge!

**Comment by calcuttj** [comment]
@knoepfel could you please remind me where to request a release of art-g4tk/larsoft with that new release?

**Comment by lgarren** [comment]
@calcuttj you could open a redmine larsoft issue.

**Pull request merged**
